version: 2
project_name: gologin-test-app
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
archives:
  - formats:
      - zip
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
release:
  disable: false
